### ISSUE TITLE
Problem with the creation of a group M +  (Without Battle.net Authenticator)

### ISSUE THREAD

**Issue by Yoptyzhka** [ChrisKader/LFMPlus#10]
*Autofill group finder information based on the creator’s keystone.  - This feature does not work with LFM+. (On the default interface everything works fine.
![default](https://user-images.githubusercontent.com/95019429/143410829-e62fb26d-43ad-4559-a548-619372bb8dc7.jpg)
![LFM+](https://user-images.githubusercontent.com/95019429/143410840-3a0e2379-e782-4700-9bbd-23020cdaa764.jpg)
 )

**Comment by ChrisKader** [comment]
Unfortunately, this is something that had to be disabled in order for LFM+ to not produce taint errors when being used.
