### ISSUE TITLE
frame not hooked

### ISSUE THREAD

**Issue by gaveer** [ChrisKader/LFMPlus#14]
Hello @ChrisKader 
when i have the raider.io addon ON , the frame if i mouse over ( green frame ) the group is not hooked into the Raider frame  ( red frame )
![Screenshot_15](https://user-images.githubusercontent.com/45834601/149856006-e245e7b1-d174-4cb7-978b-65c28f7e48ec.png)

This is without the addon LFM+ ON : 

![Screenshot_14](https://user-images.githubusercontent.com/45834601/149856048-2b2183b7-5113-4531-814f-7cb5047f588f.png)

i traid to /fstack but i cant xD mouse over must be on the group

**Comment by ChrisKader** [comment]
Man, I think you spent more time on this bug report than I did coding this addon! Nice work!

I will get this fixed today.

**Comment by ChrisKader** [comment]
Fixed in [v1.5.2](https://github.com/ChrisKader/LFMPlus/releases/tag/v1.5.2)
