### ISSUE TITLE
Display spec for group members in search results

### ISSUE THREAD

**Issue by tomrus88** [ChrisKader/LFMPlus#16]
Blizzard has added spec name (in addition to class/role) return to C_LFGList.GetSearchResultMemberInfo API in 9.2.
Please make that information displayed somewhere for M+ groups.
An example (added using custom edit in my personal addon):
<img width="477" alt="image" src="https://user-images.githubusercontent.com/12560/154772132-372462d9-09d0-4317-bfbb-da0e3cbddc61.png">

**Comment by ChrisKader** [comment]
Oh man, this makes me happy! I need to look at the 9.2 API changes overall. If only they would have added covenant info too!
