### ISSUE TITLE
Double click sign up not working

### ISSUE THREAD

**Issue by gaveer** [ChrisKader/LFMPlus#17]
Hey the Features Double click on a listing to sign up dose not work at all , could you look into the issue ?

**Comment by ChrisKader** [comment]
Type "/lfm" to open the options menu then go to UI Enhancements and toggle the check box

**Comment by gaveer** [comment]
its toggled already , but **not working**

**Comment by ChrisKader** [comment]
Fixed in [v1.5.2](https://github.com/ChrisKader/LFMPlus/releases/tag/v1.5.2)
