### ISSUE TITLE
Tazavesh dungeons filter missing

### ISSUE THREAD

**Issue by tomrus88** [ChrisKader/LFMPlus#20]
Currently 2 new Tazavesh dungeons are missing in dropdown filter menu.

**Comment by gaveer** [comment]
@tomrus88  he add them but didnt push the update into the new version :P

**Comment by strayge** [comment]
to fix current version need change [misspelling](https://github.com/ChrisKader/LFMPlus/blob/e0074937baa4c1c3b98e062f3e89b05f5ff77bd1/constants.lua#L32) `cmdID` => `cmID` in `constants.lua`

**Comment by gaveer** [comment]
@ChrisKader

**Comment by ChrisKader** [comment]
Fixed in [v1.5.2](https://github.com/ChrisKader/LFMPlus/releases/tag/v1.5.2)
