### ISSUE TITLE
WoWUp support

### ISSUE THREAD

**Issue by faku99** [ChrisKader/LFMPlus#23]
Would it be possible to release LFMPlus on a database that is WoWUp-compatible, like WoWInterface or Wago.io?

**Comment by ChrisKader** [comment]
LFMPlus has been on [Wago.io](https://addons.wago.io/addons/lfmplus/) since day 1.

This git repo can also be used to "Install from URL" from within the WowUp application.

![image](https://user-images.githubusercontent.com/633360/175115791-ef7117d4-7a3c-46aa-9085-7a92068b7f7d.png)
