### ISSUE TITLE
Minimum Score Slider not available

### ISSUE THREAD

**Issue by iMigu** [ChrisKader/LFMPlus#34]
Minimum Score Slider is not available anymore. Only shows 0 where there use to be a slider
![kuva](https://github.com/ChrisKader/LFMPlus/assets/87241192/eb469006-0425-4937-bac6-233b0a1051d1)

**Comment by ChrisKader** [comment]
Place your cursor over the number (0, not the drop down) and scroll up/down with your mouse wheel to change the value.
