### ISSUE TITLE
Not 100% sure but I think the error below is caused by LFM+

### ISSUE THREAD

**Issue by Galthariel** [ChrisKader/LFMPlus#6]
I don't use any other LFG a addon and that's why I think it's LFM+ but I can be wrong

2x [ADDON_ACTION_BLOCKED] AddOn 'Ace3' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3508: in function <FrameXML\LFGList.lua:3499>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>

**Comment by ChrisKader** [comment]
New release has been posted that should fix this and many other issues.
